/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { gitApi } from './gitApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AdvSecEnablementStatus } from './models/AdvSecEnablementStatus';
export type { AdvSecEnablementUpdate } from './models/AdvSecEnablementUpdate';
export type { AssociatedWorkItem } from './models/AssociatedWorkItem';
export type { AsyncGitOperationNotification } from './models/AsyncGitOperationNotification';
export type { AsyncRefOperationCommitLevelEventNotification } from './models/AsyncRefOperationCommitLevelEventNotification';
export type { AsyncRefOperationCompletedNotification } from './models/AsyncRefOperationCompletedNotification';
export type { AsyncRefOperationConflictNotification } from './models/AsyncRefOperationConflictNotification';
export type { AsyncRefOperationGeneralFailureNotification } from './models/AsyncRefOperationGeneralFailureNotification';
export type { AsyncRefOperationProgressNotification } from './models/AsyncRefOperationProgressNotification';
export type { AsyncRefOperationTimeoutNotification } from './models/AsyncRefOperationTimeoutNotification';
export type { Attachment } from './models/Attachment';
export type { AutoCompleteUpdatedEvent } from './models/AutoCompleteUpdatedEvent';
export type { BillableCommitter } from './models/BillableCommitter';
export type { BillableCommitterDetail } from './models/BillableCommitterDetail';
export type { BillablePusher } from './models/BillablePusher';
export type { BranchUpdatedEvent } from './models/BranchUpdatedEvent';
export type { Change } from './models/Change';
export type { ChangeCountDictionary } from './models/ChangeCountDictionary';
export type { ChangeList } from './models/ChangeList';
export type { ChangeListSearchCriteria } from './models/ChangeListSearchCriteria';
export type { CheckinNote } from './models/CheckinNote';
export type { Comment } from './models/Comment';
export type { CommentIterationContext } from './models/CommentIterationContext';
export type { CommentPosition } from './models/CommentPosition';
export type { CommentThread } from './models/CommentThread';
export type { CommentThreadContext } from './models/CommentThreadContext';
export type { CommentTrackingCriteria } from './models/CommentTrackingCriteria';
export type { CompletionErrorsEvent } from './models/CompletionErrorsEvent';
export type { DiscussionsUpdatedEvent } from './models/DiscussionsUpdatedEvent';
export type { FileContentMetadata } from './models/FileContentMetadata';
export type { FileDiff } from './models/FileDiff';
export type { FileDiffParams } from './models/FileDiffParams';
export type { FileDiffsCriteria } from './models/FileDiffsCriteria';
export type { GitAnnotatedTag } from './models/GitAnnotatedTag';
export type { GitAsyncRefOperation } from './models/GitAsyncRefOperation';
export type { GitAsyncRefOperationDetail } from './models/GitAsyncRefOperationDetail';
export type { GitAsyncRefOperationParameters } from './models/GitAsyncRefOperationParameters';
export type { GitAsyncRefOperationSource } from './models/GitAsyncRefOperationSource';
export type { GitBaseVersionDescriptor } from './models/GitBaseVersionDescriptor';
export type { GitBlobRef } from './models/GitBlobRef';
export type { GitBranchStats } from './models/GitBranchStats';
export type { GitChange } from './models/GitChange';
export type { GitCherryPick } from './models/GitCherryPick';
export type { GitCommit } from './models/GitCommit';
export type { GitCommitChanges } from './models/GitCommitChanges';
export type { GitCommitDiffs } from './models/GitCommitDiffs';
export type { GitCommitRef } from './models/GitCommitRef';
export type { GitCommitToCreate } from './models/GitCommitToCreate';
export type { GitConflict } from './models/GitConflict';
export type { GitConflictAddAdd } from './models/GitConflictAddAdd';
export type { GitConflictAddRename } from './models/GitConflictAddRename';
export type { GitConflictDeleteEdit } from './models/GitConflictDeleteEdit';
export type { GitConflictDeleteRename } from './models/GitConflictDeleteRename';
export type { GitConflictDirectoryFile } from './models/GitConflictDirectoryFile';
export type { GitConflictEditDelete } from './models/GitConflictEditDelete';
export type { GitConflictEditEdit } from './models/GitConflictEditEdit';
export type { GitConflictFileDirectory } from './models/GitConflictFileDirectory';
export type { GitConflictRename1to2 } from './models/GitConflictRename1to2';
export type { GitConflictRename2to1 } from './models/GitConflictRename2to1';
export type { GitConflictRenameAdd } from './models/GitConflictRenameAdd';
export type { GitConflictRenameDelete } from './models/GitConflictRenameDelete';
export type { GitConflictRenameRename } from './models/GitConflictRenameRename';
export type { GitConflictUpdateResult } from './models/GitConflictUpdateResult';
export type { GitDeletedRepository } from './models/GitDeletedRepository';
export type { GitFilePathsCollection } from './models/GitFilePathsCollection';
export type { GitForkOperationStatusDetail } from './models/GitForkOperationStatusDetail';
export type { GitForkRef } from './models/GitForkRef';
export type { GitForkSyncRequest } from './models/GitForkSyncRequest';
export type { GitForkSyncRequestParameters } from './models/GitForkSyncRequestParameters';
export type { GitForkTeamProjectReference } from './models/GitForkTeamProjectReference';
export type { GitImportFailedEvent } from './models/GitImportFailedEvent';
export type { GitImportGitSource } from './models/GitImportGitSource';
export type { GitImportRequest } from './models/GitImportRequest';
export type { GitImportRequestParameters } from './models/GitImportRequestParameters';
export type { GitImportStatusDetail } from './models/GitImportStatusDetail';
export type { GitImportSucceededEvent } from './models/GitImportSucceededEvent';
export type { GitImportTfvcSource } from './models/GitImportTfvcSource';
export type { GitItem } from './models/GitItem';
export type { GitItemDescriptor } from './models/GitItemDescriptor';
export type { GitItemRequestData } from './models/GitItemRequestData';
export type { GitLastChangeItem } from './models/GitLastChangeItem';
export type { GitLastChangeTreeItems } from './models/GitLastChangeTreeItems';
export type { GitMerge } from './models/GitMerge';
export type { GitMergeOperationStatusDetail } from './models/GitMergeOperationStatusDetail';
export type { GitMergeOriginRef } from './models/GitMergeOriginRef';
export type { GitMergeParameters } from './models/GitMergeParameters';
export type { GitObject } from './models/GitObject';
export type { GitPathAction } from './models/GitPathAction';
export type { GitPathToItemsCollection } from './models/GitPathToItemsCollection';
export type { GitPolicyConfigurationResponse } from './models/GitPolicyConfigurationResponse';
export type { GitPullRequest } from './models/GitPullRequest';
export type { GitPullRequestChange } from './models/GitPullRequestChange';
export type { GitPullRequestCommentThread } from './models/GitPullRequestCommentThread';
export type { GitPullRequestCommentThreadContext } from './models/GitPullRequestCommentThreadContext';
export type { GitPullRequestCompletionOptions } from './models/GitPullRequestCompletionOptions';
export type { GitPullRequestIteration } from './models/GitPullRequestIteration';
export type { GitPullRequestIterationChanges } from './models/GitPullRequestIterationChanges';
export type { GitPullRequestMergeOptions } from './models/GitPullRequestMergeOptions';
export type { GitPullRequestQuery } from './models/GitPullRequestQuery';
export type { GitPullRequestQueryInput } from './models/GitPullRequestQueryInput';
export type { GitPullRequestReviewFileContentInfo } from './models/GitPullRequestReviewFileContentInfo';
export type { GitPullRequestSearchCriteria } from './models/GitPullRequestSearchCriteria';
export type { GitPullRequestStatus } from './models/GitPullRequestStatus';
export type { GitPush } from './models/GitPush';
export type { GitPushEventData } from './models/GitPushEventData';
export type { GitPushRef } from './models/GitPushRef';
export type { GitPushSearchCriteria } from './models/GitPushSearchCriteria';
export type { GitQueryBranchStatsCriteria } from './models/GitQueryBranchStatsCriteria';
export type { GitQueryCommitsCriteria } from './models/GitQueryCommitsCriteria';
export type { GitQueryRefsCriteria } from './models/GitQueryRefsCriteria';
export type { GitRecycleBinRepositoryDetails } from './models/GitRecycleBinRepositoryDetails';
export type { GitRef } from './models/GitRef';
export type { GitRefFavorite } from './models/GitRefFavorite';
export type { GitRefUpdate } from './models/GitRefUpdate';
export type { GitRefUpdateResult } from './models/GitRefUpdateResult';
export type { GitRepository } from './models/GitRepository';
export type { GitRepositoryCreateOptions } from './models/GitRepositoryCreateOptions';
export type { GitRepositoryRef } from './models/GitRepositoryRef';
export type { GitRepositoryStats } from './models/GitRepositoryStats';
export type { GitResolution } from './models/GitResolution';
export type { GitResolutionMergeContent } from './models/GitResolutionMergeContent';
export type { GitResolutionPathConflict } from './models/GitResolutionPathConflict';
export type { GitResolutionPickOneAction } from './models/GitResolutionPickOneAction';
export type { GitResolutionRename1to2 } from './models/GitResolutionRename1to2';
export type { GitRevert } from './models/GitRevert';
export type { GitStatus } from './models/GitStatus';
export type { GitStatusContext } from './models/GitStatusContext';
export type { GitSuggestion } from './models/GitSuggestion';
export type { GitTargetVersionDescriptor } from './models/GitTargetVersionDescriptor';
export type { GitTemplate } from './models/GitTemplate';
export type { GitTreeDiff } from './models/GitTreeDiff';
export type { GitTreeDiffEntry } from './models/GitTreeDiffEntry';
export type { GitTreeDiffResponse } from './models/GitTreeDiffResponse';
export type { GitTreeEntryRef } from './models/GitTreeEntryRef';
export type { GitTreeRef } from './models/GitTreeRef';
export type { GitUserDate } from './models/GitUserDate';
export type { GitVersionDescriptor } from './models/GitVersionDescriptor';
export type { GlobalGitRepositoryKey } from './models/GlobalGitRepositoryKey';
export type { GraphSubjectBase } from './models/GraphSubjectBase';
export type { HistoryEntry } from './models/HistoryEntry';
export type { IdentityRef } from './models/IdentityRef';
export type { IdentityRefWithVote } from './models/IdentityRefWithVote';
export type { ImportRepositoryValidation } from './models/ImportRepositoryValidation';
export type { IncludedGitCommit } from './models/IncludedGitCommit';
export type { IsDraftUpdatedEvent } from './models/IsDraftUpdatedEvent';
export type { ItemContent } from './models/ItemContent';
export type { ItemDetailsOptions } from './models/ItemDetailsOptions';
export type { ItemModel } from './models/ItemModel';
export type { JsonPatchDocument } from './models/JsonPatchDocument';
export type { JsonPatchOperation } from './models/JsonPatchOperation';
export type { LabelsUpdatedEvent } from './models/LabelsUpdatedEvent';
export type { LineDiffBlock } from './models/LineDiffBlock';
export type { MergeCompletedEvent } from './models/MergeCompletedEvent';
export type { PolicyConfiguration } from './models/PolicyConfiguration';
export type { PolicyConfigurationRef } from './models/PolicyConfigurationRef';
export type { PolicyEvaluationUpdatedEvent } from './models/PolicyEvaluationUpdatedEvent';
export type { PolicyTypeRef } from './models/PolicyTypeRef';
export type { PropertiesCollection } from './models/PropertiesCollection';
export type { PullRequestCreatedEvent } from './models/PullRequestCreatedEvent';
export type { PullRequestTabExtensionConfig } from './models/PullRequestTabExtensionConfig';
export type { RealTimePullRequestEvent } from './models/RealTimePullRequestEvent';
export type { ReferenceLinks } from './models/ReferenceLinks';
export type { ResourceRef } from './models/ResourceRef';
export type { RetargetEvent } from './models/RetargetEvent';
export type { ReviewersUpdatedEvent } from './models/ReviewersUpdatedEvent';
export type { ReviewersVotesResetEvent } from './models/ReviewersVotesResetEvent';
export type { ReviewerVoteUpdatedEvent } from './models/ReviewerVoteUpdatedEvent';
export type { ShareNotificationContext } from './models/ShareNotificationContext';
export type { SourceToTargetRef } from './models/SourceToTargetRef';
export type { StatusAddedEvent } from './models/StatusAddedEvent';
export type { StatusesDeletedEvent } from './models/StatusesDeletedEvent';
export type { StatusUpdatedEvent } from './models/StatusUpdatedEvent';
export type { SupportedIde } from './models/SupportedIde';
export type { TeamProjectCollectionReference } from './models/TeamProjectCollectionReference';
export type { TeamProjectReference } from './models/TeamProjectReference';
export type { TfvcBranch } from './models/TfvcBranch';
export type { TfvcBranchMapping } from './models/TfvcBranchMapping';
export type { TfvcBranchRef } from './models/TfvcBranchRef';
export type { TfvcChange } from './models/TfvcChange';
export type { TfvcChangeset } from './models/TfvcChangeset';
export type { TfvcChangesetRef } from './models/TfvcChangesetRef';
export type { TfvcChangesetSearchCriteria } from './models/TfvcChangesetSearchCriteria';
export type { TfvcChangesetsRequestData } from './models/TfvcChangesetsRequestData';
export type { TfvcCheckinEventData } from './models/TfvcCheckinEventData';
export type { TfvcHistoryEntry } from './models/TfvcHistoryEntry';
export type { TfvcItem } from './models/TfvcItem';
export type { TfvcItemDescriptor } from './models/TfvcItemDescriptor';
export type { TfvcItemPreviousHash } from './models/TfvcItemPreviousHash';
export type { TfvcItemRequestData } from './models/TfvcItemRequestData';
export type { TfvcLabel } from './models/TfvcLabel';
export type { TfvcLabelRef } from './models/TfvcLabelRef';
export type { TfvcLabelRequestData } from './models/TfvcLabelRequestData';
export type { TfvcMappingFilter } from './models/TfvcMappingFilter';
export type { TfvcMergeSource } from './models/TfvcMergeSource';
export type { TfvcPolicyFailureInfo } from './models/TfvcPolicyFailureInfo';
export type { TfvcPolicyOverrideInfo } from './models/TfvcPolicyOverrideInfo';
export type { TfvcShallowBranchRef } from './models/TfvcShallowBranchRef';
export type { TfvcShelveset } from './models/TfvcShelveset';
export type { TfvcShelvesetRef } from './models/TfvcShelvesetRef';
export type { TfvcShelvesetRequestData } from './models/TfvcShelvesetRequestData';
export type { TfvcStatistics } from './models/TfvcStatistics';
export type { TfvcVersionDescriptor } from './models/TfvcVersionDescriptor';
export type { TitleDescriptionUpdatedEvent } from './models/TitleDescriptionUpdatedEvent';
export type { UpdateRefsRequest } from './models/UpdateRefsRequest';
export type { VersionControlProjectInfo } from './models/VersionControlProjectInfo';
export type { VersionedPolicyConfigurationRef } from './models/VersionedPolicyConfigurationRef';
export type { VssJsonCollectionWrapper } from './models/VssJsonCollectionWrapper';
export type { VssJsonCollectionWrapperBase } from './models/VssJsonCollectionWrapperBase';
export type { WebApiCreateTagRequestData } from './models/WebApiCreateTagRequestData';
export type { WebApiTagDefinition } from './models/WebApiTagDefinition';

export { AnnotatedTagsService } from './services/AnnotatedTagsService';
export { BlobsService } from './services/BlobsService';
export { CherryPicksService } from './services/CherryPicksService';
export { CommitsService } from './services/CommitsService';
export { DiffsService } from './services/DiffsService';
export { ForksService } from './services/ForksService';
export { ImportRequestsService } from './services/ImportRequestsService';
export { ItemsService } from './services/ItemsService';
export { MergeBasesService } from './services/MergeBasesService';
export { MergesService } from './services/MergesService';
export { PolicyConfigurationsService } from './services/PolicyConfigurationsService';
export { PullRequestAttachmentsService } from './services/PullRequestAttachmentsService';
export { PullRequestCommentLikesService } from './services/PullRequestCommentLikesService';
export { PullRequestCommitsService } from './services/PullRequestCommitsService';
export { PullRequestIterationChangesService } from './services/PullRequestIterationChangesService';
export { PullRequestIterationsService } from './services/PullRequestIterationsService';
export { PullRequestIterationStatusesService } from './services/PullRequestIterationStatusesService';
export { PullRequestLabelsService } from './services/PullRequestLabelsService';
export { PullRequestPropertiesService } from './services/PullRequestPropertiesService';
export { PullRequestQueryService } from './services/PullRequestQueryService';
export { PullRequestReviewersService } from './services/PullRequestReviewersService';
export { PullRequestsService } from './services/PullRequestsService';
export { PullRequestShareService } from './services/PullRequestShareService';
export { PullRequestStatusesService } from './services/PullRequestStatusesService';
export { PullRequestThreadCommentsService } from './services/PullRequestThreadCommentsService';
export { PullRequestThreadsService } from './services/PullRequestThreadsService';
export { PullRequestWorkItemsService } from './services/PullRequestWorkItemsService';
export { PushesService } from './services/PushesService';
export { RefsService } from './services/RefsService';
export { RefsFavoritesService } from './services/RefsFavoritesService';
export { RefsFavoritesForProjectService } from './services/RefsFavoritesForProjectService';
export { RepositoriesService } from './services/RepositoriesService';
export { RevertsService } from './services/RevertsService';
export { StatsService } from './services/StatsService';
export { StatusesService } from './services/StatusesService';
export { SuggestionsService } from './services/SuggestionsService';
export { TreesService } from './services/TreesService';
