/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export type Avatar = {
    isAutoGenerated?: boolean;
    size?: 'small' | 'medium' | 'large';
    timeStamp?: string;
    value?: Array<string>;
};

