/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { witApi } from './witApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AccountMyWorkResult } from './models/AccountMyWorkResult';
export type { AccountRecentActivityWorkItemModel } from './models/AccountRecentActivityWorkItemModel';
export type { AccountRecentActivityWorkItemModel2 } from './models/AccountRecentActivityWorkItemModel2';
export type { AccountRecentActivityWorkItemModelBase } from './models/AccountRecentActivityWorkItemModelBase';
export type { AccountRecentMentionWorkItemModel } from './models/AccountRecentMentionWorkItemModel';
export type { AccountWorkWorkItemModel } from './models/AccountWorkWorkItemModel';
export type { ArtifactUriQuery } from './models/ArtifactUriQuery';
export type { ArtifactUriQueryResult } from './models/ArtifactUriQueryResult';
export type { AttachmentReference } from './models/AttachmentReference';
export type { Comment } from './models/Comment';
export type { CommentCreate } from './models/CommentCreate';
export type { CommentList } from './models/CommentList';
export type { CommentMention } from './models/CommentMention';
export type { CommentReaction } from './models/CommentReaction';
export type { CommentUpdate } from './models/CommentUpdate';
export type { CommentVersion } from './models/CommentVersion';
export type { EmailRecipients } from './models/EmailRecipients';
export type { ExternalDeployment } from './models/ExternalDeployment';
export type { ExternalEnvironment } from './models/ExternalEnvironment';
export type { ExternalPipeline } from './models/ExternalPipeline';
export type { FieldDependentRule } from './models/FieldDependentRule';
export type { GraphSubjectBase } from './models/GraphSubjectBase';
export type { IdentityRef } from './models/IdentityRef';
export type { IdentityReference } from './models/IdentityReference';
export type { JsonPatchDocument } from './models/JsonPatchDocument';
export type { JsonPatchOperation } from './models/JsonPatchOperation';
export type { Link } from './models/Link';
export type { MailMessage } from './models/MailMessage';
export type { ProcessIdModel } from './models/ProcessIdModel';
export type { ProcessMigrationResultModel } from './models/ProcessMigrationResultModel';
export type { ProjectWorkItemStateColors } from './models/ProjectWorkItemStateColors';
export type { ProvisioningResult } from './models/ProvisioningResult';
export type { QueryBatchGetRequest } from './models/QueryBatchGetRequest';
export type { QueryHierarchyItem } from './models/QueryHierarchyItem';
export type { QueryHierarchyItemsResult } from './models/QueryHierarchyItemsResult';
export type { ReferenceLinks } from './models/ReferenceLinks';
export type { ReportingWorkItemLinksBatch } from './models/ReportingWorkItemLinksBatch';
export type { ReportingWorkItemRevisionsBatch } from './models/ReportingWorkItemRevisionsBatch';
export type { ReportingWorkItemRevisionsFilter } from './models/ReportingWorkItemRevisionsFilter';
export type { SendMailBody } from './models/SendMailBody';
export type { StreamedBatch } from './models/StreamedBatch';
export type { TeamContext } from './models/TeamContext';
export type { UpdateWorkItemField } from './models/UpdateWorkItemField';
export type { VssJsonCollectionWrapper } from './models/VssJsonCollectionWrapper';
export type { VssJsonCollectionWrapperBase } from './models/VssJsonCollectionWrapperBase';
export type { Wiql } from './models/Wiql';
export type { WorkArtifactLink } from './models/WorkArtifactLink';
export type { WorkItem } from './models/WorkItem';
export type { WorkItemBatchGetRequest } from './models/WorkItemBatchGetRequest';
export type { WorkItemClassificationNode } from './models/WorkItemClassificationNode';
export type { WorkItemComment } from './models/WorkItemComment';
export type { WorkItemComments } from './models/WorkItemComments';
export type { WorkItemCommentVersionRef } from './models/WorkItemCommentVersionRef';
export type { WorkItemDelete } from './models/WorkItemDelete';
export type { WorkItemDeleteReference } from './models/WorkItemDeleteReference';
export type { WorkItemDeleteShallowReference } from './models/WorkItemDeleteShallowReference';
export type { WorkItemDeleteUpdate } from './models/WorkItemDeleteUpdate';
export type { WorkItemField } from './models/WorkItemField';
export type { WorkItemFieldOperation } from './models/WorkItemFieldOperation';
export type { WorkItemFieldReference } from './models/WorkItemFieldReference';
export type { WorkItemFieldUpdate } from './models/WorkItemFieldUpdate';
export type { WorkItemHistory } from './models/WorkItemHistory';
export type { WorkItemIcon } from './models/WorkItemIcon';
export type { WorkItemLink } from './models/WorkItemLink';
export type { WorkItemNextStateOnTransition } from './models/WorkItemNextStateOnTransition';
export type { WorkItemQueryClause } from './models/WorkItemQueryClause';
export type { WorkItemQueryResult } from './models/WorkItemQueryResult';
export type { WorkItemQuerySortColumn } from './models/WorkItemQuerySortColumn';
export type { WorkItemReference } from './models/WorkItemReference';
export type { WorkItemRelation } from './models/WorkItemRelation';
export type { WorkItemRelationType } from './models/WorkItemRelationType';
export type { WorkItemRelationUpdates } from './models/WorkItemRelationUpdates';
export type { WorkItemStateColor } from './models/WorkItemStateColor';
export type { WorkItemStateTransition } from './models/WorkItemStateTransition';
export type { WorkItemTagDefinition } from './models/WorkItemTagDefinition';
export type { WorkItemTemplate } from './models/WorkItemTemplate';
export type { WorkItemTemplateReference } from './models/WorkItemTemplateReference';
export type { WorkItemTrackingReference } from './models/WorkItemTrackingReference';
export type { WorkItemTrackingResource } from './models/WorkItemTrackingResource';
export type { WorkItemTrackingResourceReference } from './models/WorkItemTrackingResourceReference';
export type { WorkItemType } from './models/WorkItemType';
export type { WorkItemTypeCategory } from './models/WorkItemTypeCategory';
export type { WorkItemTypeColor } from './models/WorkItemTypeColor';
export type { WorkItemTypeColorAndIcon } from './models/WorkItemTypeColorAndIcon';
export type { WorkItemTypeFieldInstance } from './models/WorkItemTypeFieldInstance';
export type { WorkItemTypeFieldInstanceBase } from './models/WorkItemTypeFieldInstanceBase';
export type { WorkItemTypeFieldWithReferences } from './models/WorkItemTypeFieldWithReferences';
export type { WorkItemTypeReference } from './models/WorkItemTypeReference';
export type { WorkItemTypeStateColors } from './models/WorkItemTypeStateColors';
export type { WorkItemTypeTemplate } from './models/WorkItemTypeTemplate';
export type { WorkItemTypeTemplateUpdateModel } from './models/WorkItemTypeTemplateUpdateModel';
export type { WorkItemUpdate } from './models/WorkItemUpdate';

export { AccountMyWorkRecentActivityService } from './services/AccountMyWorkRecentActivityService';
export { ArtifactLinkTypesService } from './services/ArtifactLinkTypesService';
export { ArtifactUriQueryService } from './services/ArtifactUriQueryService';
export { AttachmentsService } from './services/AttachmentsService';
export { ClassificationNodesService } from './services/ClassificationNodesService';
export { CommentReactionsEngagedUsersService } from './services/CommentReactionsEngagedUsersService';
export { CommentsService } from './services/CommentsService';
export { CommentsReactionsService } from './services/CommentsReactionsService';
export { CommentsVersionsService } from './services/CommentsVersionsService';
export { FieldsService } from './services/FieldsService';
export { ProjectProcessMigrationService } from './services/ProjectProcessMigrationService';
export { QueriesService } from './services/QueriesService';
export { RecyclebinService } from './services/RecyclebinService';
export { ReportingWorkItemLinksService } from './services/ReportingWorkItemLinksService';
export { ReportingWorkItemRevisionsService } from './services/ReportingWorkItemRevisionsService';
export { RevisionsService } from './services/RevisionsService';
export { SendMailService } from './services/SendMailService';
export { TagsService } from './services/TagsService';
export { TemplatesService } from './services/TemplatesService';
export { UpdatesService } from './services/UpdatesService';
export { WiqlService } from './services/WiqlService';
export { WorkItemIconsService } from './services/WorkItemIconsService';
export { WorkItemRelationTypesService } from './services/WorkItemRelationTypesService';
export { WorkItemRevisionsDiscussionsService } from './services/WorkItemRevisionsDiscussionsService';
export { WorkItemsService } from './services/WorkItemsService';
export { WorkItemTransitionsService } from './services/WorkItemTransitionsService';
export { WorkItemTypeCategoriesService } from './services/WorkItemTypeCategoriesService';
export { WorkItemTypesService } from './services/WorkItemTypesService';
export { WorkItemTypesFieldService } from './services/WorkItemTypesFieldService';
export { WorkItemTypeStatesService } from './services/WorkItemTypeStatesService';
