/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { testResultsApi } from './testResultsApi';

export { ApiError } from './core/ApiError';
export { BaseHttpRequest } from './core/BaseHttpRequest';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AggregatedDataForResultTrend } from './models/AggregatedDataForResultTrend';
export type { AggregatedResultDetailsByOutcome } from './models/AggregatedResultDetailsByOutcome';
export type { AggregatedResultsAnalysis } from './models/AggregatedResultsAnalysis';
export type { AggregatedResultsByOutcome } from './models/AggregatedResultsByOutcome';
export type { AggregatedResultsDifference } from './models/AggregatedResultsDifference';
export type { AggregatedRunsByOutcome } from './models/AggregatedRunsByOutcome';
export type { AggregatedRunsByState } from './models/AggregatedRunsByState';
export type { Attachment } from './models/Attachment';
export type { BuildConfiguration } from './models/BuildConfiguration';
export type { BuildCoverage } from './models/BuildCoverage';
export type { BuildReference } from './models/BuildReference';
export type { CodeCoverageData } from './models/CodeCoverageData';
export type { CodeCoverageStatistics } from './models/CodeCoverageStatistics';
export type { CodeCoverageSummary } from './models/CodeCoverageSummary';
export type { CoverageStatistics } from './models/CoverageStatistics';
export type { CustomTestField } from './models/CustomTestField';
export type { DtlEnvironmentDetails } from './models/DtlEnvironmentDetails';
export type { FailingSince } from './models/FailingSince';
export type { FieldDetailsForTestResults } from './models/FieldDetailsForTestResults';
export type { FileCoverageRequest } from './models/FileCoverageRequest';
export type { FlakyDetection } from './models/FlakyDetection';
export type { FlakyDetectionPipelines } from './models/FlakyDetectionPipelines';
export type { FlakySettings } from './models/FlakySettings';
export type { FunctionCoverage } from './models/FunctionCoverage';
export type { GraphSubjectBase } from './models/GraphSubjectBase';
export type { IdentityRef } from './models/IdentityRef';
export type { JobReference } from './models/JobReference';
export type { ModuleCoverage } from './models/ModuleCoverage';
export type { NewTestResultLoggingSettings } from './models/NewTestResultLoggingSettings';
export type { PhaseReference } from './models/PhaseReference';
export type { PipelineReference } from './models/PipelineReference';
export type { PipelineTestMetrics } from './models/PipelineTestMetrics';
export type { QueryModel } from './models/QueryModel';
export type { ReferenceLinks } from './models/ReferenceLinks';
export type { ReleaseReference } from './models/ReleaseReference';
export type { ResultsAnalysis } from './models/ResultsAnalysis';
export type { ResultsFilter } from './models/ResultsFilter';
export type { ResultsSummaryByOutcome } from './models/ResultsSummaryByOutcome';
export type { ResultSummary } from './models/ResultSummary';
export type { RunCreateModel } from './models/RunCreateModel';
export type { RunFilter } from './models/RunFilter';
export type { RunStatistic } from './models/RunStatistic';
export type { RunSummary } from './models/RunSummary';
export type { RunSummaryModel } from './models/RunSummaryModel';
export type { RunUpdateModel } from './models/RunUpdateModel';
export type { ShallowReference } from './models/ShallowReference';
export type { ShallowTestCaseResult } from './models/ShallowTestCaseResult';
export type { SharedStepModel } from './models/SharedStepModel';
export type { StageReference } from './models/StageReference';
export type { TeamProjectReference } from './models/TeamProjectReference';
export type { TestActionResultModel } from './models/TestActionResultModel';
export type { TestAttachment } from './models/TestAttachment';
export type { TestAttachmentReference } from './models/TestAttachmentReference';
export type { TestAttachmentRequestModel } from './models/TestAttachmentRequestModel';
export type { TestCaseResult } from './models/TestCaseResult';
export type { TestCaseResultAttachmentModel } from './models/TestCaseResultAttachmentModel';
export type { TestCaseResultIdentifier } from './models/TestCaseResultIdentifier';
export type { TestEnvironment } from './models/TestEnvironment';
export type { TestFailureDetails } from './models/TestFailureDetails';
export type { TestFailuresAnalysis } from './models/TestFailuresAnalysis';
export type { TestFlakyIdentifier } from './models/TestFlakyIdentifier';
export type { TestHistoryQuery } from './models/TestHistoryQuery';
export type { TestIterationDetailsModel } from './models/TestIterationDetailsModel';
export type { TestLog } from './models/TestLog';
export type { TestLogReference } from './models/TestLogReference';
export type { TestLogStoreAttachment } from './models/TestLogStoreAttachment';
export type { TestLogStoreAttachmentReference } from './models/TestLogStoreAttachmentReference';
export type { TestLogStoreEndpointDetails } from './models/TestLogStoreEndpointDetails';
export type { TestMessageLogDetails } from './models/TestMessageLogDetails';
export type { TestMethod } from './models/TestMethod';
export type { TestOperationReference } from './models/TestOperationReference';
export type { TestResolutionState } from './models/TestResolutionState';
export type { TestResultDocument } from './models/TestResultDocument';
export type { TestResultFailuresAnalysis } from './models/TestResultFailuresAnalysis';
export type { TestResultFailureType } from './models/TestResultFailureType';
export type { TestResultFailureTypeRequestModel } from './models/TestResultFailureTypeRequestModel';
export type { TestResultHistory } from './models/TestResultHistory';
export type { TestResultHistoryDetailsForGroup } from './models/TestResultHistoryDetailsForGroup';
export type { TestResultHistoryForGroup } from './models/TestResultHistoryForGroup';
export type { TestResultMetaData } from './models/TestResultMetaData';
export type { TestResultMetaDataUpdateInput } from './models/TestResultMetaDataUpdateInput';
export type { TestResultModelBase } from './models/TestResultModelBase';
export type { TestResultParameterModel } from './models/TestResultParameterModel';
export type { TestResultPayload } from './models/TestResultPayload';
export type { TestResultsContext } from './models/TestResultsContext';
export type { TestResultsDetails } from './models/TestResultsDetails';
export type { TestResultsDetailsForGroup } from './models/TestResultsDetailsForGroup';
export type { TestResultsQuery } from './models/TestResultsQuery';
export type { TestResultsSettings } from './models/TestResultsSettings';
export type { TestResultSummary } from './models/TestResultSummary';
export type { TestResultsUpdateSettings } from './models/TestResultsUpdateSettings';
export type { TestResultTrendFilter } from './models/TestResultTrendFilter';
export type { TestRun } from './models/TestRun';
export type { TestRunCoverage } from './models/TestRunCoverage';
export type { TestRunStatistic } from './models/TestRunStatistic';
export type { TestSettings } from './models/TestSettings';
export type { TestSubResult } from './models/TestSubResult';
export type { TestSummaryForWorkItem } from './models/TestSummaryForWorkItem';
export type { TestTag } from './models/TestTag';
export type { TestTagSummary } from './models/TestTagSummary';
export type { TestTagsUpdateModel } from './models/TestTagsUpdateModel';
export type { TestToWorkItemLinks } from './models/TestToWorkItemLinks';
export type { VssJsonCollectionWrapper } from './models/VssJsonCollectionWrapper';
export type { VssJsonCollectionWrapperBase } from './models/VssJsonCollectionWrapperBase';
export type { WorkItemReference } from './models/WorkItemReference';
export type { WorkItemToTestLinks } from './models/WorkItemToTestLinks';

export { AttachmentsService } from './services/AttachmentsService';
export { BugsService } from './services/BugsService';
export { CodecoverageService } from './services/CodecoverageService';
export { FilecoverageService } from './services/FilecoverageService';
export { HistoryService } from './services/HistoryService';
export { MessageLogsService } from './services/MessageLogsService';
export { MetricsService } from './services/MetricsService';
export { ResultdetailsbybuildService } from './services/ResultdetailsbybuildService';
export { ResultdetailsbyreleaseService } from './services/ResultdetailsbyreleaseService';
export { ResultDocumentService } from './services/ResultDocumentService';
export { ResultgroupsbybuildService } from './services/ResultgroupsbybuildService';
export { ResultgroupsbyreleaseService } from './services/ResultgroupsbyreleaseService';
export { ResultMetaDataService } from './services/ResultMetaDataService';
export { ResultsService } from './services/ResultsService';
export { ResultsbybuildService } from './services/ResultsbybuildService';
export { ResultsbypipelineService } from './services/ResultsbypipelineService';
export { ResultsbyreleaseService } from './services/ResultsbyreleaseService';
export { ResultsgroupDetailsService } from './services/ResultsgroupDetailsService';
export { ResultsummarybybuildService } from './services/ResultsummarybybuildService';
export { ResultsummarybypipelineService } from './services/ResultsummarybypipelineService';
export { ResultsummarybyreleaseService } from './services/ResultsummarybyreleaseService';
export { ResultsummarybyrequirementService } from './services/ResultsummarybyrequirementService';
export { ResultTrendByBuildService } from './services/ResultTrendByBuildService';
export { ResultTrendByReleaseService } from './services/ResultTrendByReleaseService';
export { RunsService } from './services/RunsService';
export { RunsummaryService } from './services/RunsummaryService';
export { SettingsService } from './services/SettingsService';
export { SimilarTestResultsService } from './services/SimilarTestResultsService';
export { StatisticsService } from './services/StatisticsService';
export { StatusService } from './services/StatusService';
export { TagsService } from './services/TagsService';
export { TagsummaryService } from './services/TagsummaryService';
export { TestattachmentsService } from './services/TestattachmentsService';
export { TestfailuretypeService } from './services/TestfailuretypeService';
export { TestHistoryService } from './services/TestHistoryService';
export { TestlogService } from './services/TestlogService';
export { TestlogstoreendpointService } from './services/TestlogstoreendpointService';
export { TestsettingsService } from './services/TestsettingsService';
export { WorkitemsService } from './services/WorkitemsService';
