/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ArtifactProperties } from './ArtifactProperties';
import type { ArtifactScope } from './ArtifactScope';
import type { IdentityRef } from './IdentityRef';
import type { ReferenceLinks } from './ReferenceLinks';
/**
 * Implementation of Favorite contract following modern storage
 */
export type Favorite = {
    /**
     * Links to the resources associated to the underlying artifact.
     */
    _links?: ReferenceLinks;
    /**
     * ID of the favorited artifact, unique in context of this artifact type.
     */
    artifactId?: string;
    /**
     * Indicates if the artifact described by this favorite could not be located.
     */
    artifactIsDeleted?: boolean;
    /**
     * Last known name of the artifact.
     */
    artifactName?: string;
    /**
     * A dictionary of cached properties describing a Favorited artifact. Structure is generated by the service-side feature metadata provider handling this Artifact Type.
     */
    artifactProperties?: ArtifactProperties;
    /**
     * Artifact Scope - This object describes where an artifact is contained. e.g. Project Mandatory param for creating all favorites.
     */
    artifactScope?: ArtifactScope;
    /**
     * Type of artifact.
     */
    artifactType?: string;
    /**
     * Date and time this Favorite was created on server.
     */
    creationDate?: string;
    /**
     * Unique Id of the favorite item, defined by server at creation time.
     */
    id?: string;
    /**
     * User identity, defined by server, based on active user context.
     */
    owner?: IdentityRef;
    /**
     * Fully-Qualified link to this Resource
     */
    url?: string;
};

